name: 💡 我有新点子或者改进建议
description: 对yuque-dl有新的想法或者需要改进的地方...
labels: [feature request]
body:
  - type: textarea
    attributes:
      label: 请详细告知你的新点子：
      placeholder: |
        1. 您期望能够实现什么功能。

        2. 您的理由（如：我一直被什么问题困扰……）。
    validations:
      required: true
